### ISSUE TITLE
Junit test stability problems (SqLiteDbTest)

### ISSUE THREAD

**Issue by ProgrammingAtDawn** [bmarwell/ExperienceBank3#3]
in setUp() somtimes
`config.getSqLiteDbFileName().delete();`
fails do delete the database file.

this leads to followup errors like failing in testSqLite
`Assert.assertEquals(0, countPlayersInDatabase);`

Happens especially when running the tests multiple times, change maybe to 
`Assert.assertTrue("Could not delete database file", config.getSqLiteDbFileName().delete());`
and fix the underlying problem (file still opened elsewhere)

Also 
`Assert.assertTrue(10000 > duration);`
sometimes failes on slow machines.

**Comment by bmarwell** [comment]
I'd be happy to see pull requests. :-)

**Comment by bmarwell** [comment]
Closing for now, as this might be fixed.
